docker run -e CX_APIKEY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwNzExMDZkNS0xM2FlLTRlYTgtYTcwOC1kYTUwZmQ3ZTRlNWIifQ.eyJpYXQiOjE2NzA1MzczMTcsImp0aSI6ImIzYmUwNWQwLTgxYzItNGFmMi04ZGFjLWJlNGQzNGFkN2E3YiIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvY3hfYXN0X3NlX2FsbGVuZ2F5X2RlbW9fbmEiLCJhdWQiOiJodHRwczovL2lhbS5jaGVja21hcngubmV0L2F1dGgvcmVhbG1zL2N4X2FzdF9zZV9hbGxlbmdheV9kZW1vX25hIiwic3ViIjoiZWEzNzBmNzYtZDVhMS00MTI0LWIxZjEtYmRjMjBiNmYzZDViIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImFzdC1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiNzljOGU4OGUtOTQzYy00NzJjLWIwMzctOGI5MjBhZTg1M2U1Iiwic2NvcGUiOiIgb2ZmbGluZV9hY2Nlc3MiLCJzaWQiOiI3OWM4ZTg4ZS05NDNjLTQ3MmMtYjAzNy04YjkyMGFlODUzZTUifQ.dETMAIKLm_sNczTwzRwaNDj2bDDLEyJVuPNqxoMecRM \
  -v $(pwd):/demo checkmarx/dast:latest \
  web \
  --environment-id=e64ac486-f2e3-486e-8757-fece216af179 \
  --config=/demo/gin_juice.yaml \
  --base-url=https://ast.checkmarx.net/  \
  --output=/demo/test_output \
  --timeout=100000 \
  --update-interval=10 \
  --jvm-properties=-Xmx3G \
  --log-level=info \
  --verbose \
  --retry=3 \
  --retry-delay=20 \
  --fail-on HIGH \
